version: '3'
services:

  proxy:
    image: nginx:alpine
    logging:
      driver: none
    depends_on:
      - "client"
      - "api"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  client:
    build: 
      context: ../client
      dockerfile: Dockerfile

  api:
    build: 
      context: ../api
      dockerfile: Dockerfile